# Generated by Django 4.1.2 on 2022-10-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='banner',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(default='default', help_text='270x300', upload_to='brand_logos'),
        ),
    ]
