# Generated by Django 4.1.2 on 2022-10-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_adnroid',
            field=models.BooleanField(default=None),
        ),
    ]
