# Generated by Django 4.1.2 on 2022-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_is_adnroid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_adnroid',
        ),
        migrations.AddField(
            model_name='brand',
            name='Androind',
            field=models.BooleanField(default=None),
        ),
    ]
