# Generated by Django 4.1.2 on 2022-10-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_is_adnroid_brand_androind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='ads')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ads_product', to='shop.product')),
            ],
        ),
    ]
