# Generated by Django 4.1.2 on 2022-10-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
    ]
