# Generated by Django 4.1.2 on 2022-10-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_superuser_alter_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='State',
            new_name='state',
        ),
    ]
